name: Build and Deploy to Azure

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name jumpgavinreg

      - name: Build and Push Image
        run: |
          docker build -t jumpgavinreg.azurecr.io/jump-app:${{ github.sha }} .
          docker push jumpgavinreg.azurecr.io/jump-app:${{ github.sha }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: jumpgavinreg
          containerAppName: jump-web-server
          resourceGroup: JumpAssessment-RG
          imageToDeploy: jumpgavinreg.azurecr.io/jump-app:${{ github.sha }}
          targetPort: 8080